FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY memesensei ./memesensei
ENV CORE_API_URL="http://core:8000"
CMD ["python", "-m", "memesensei.telegram.bot"]
